### ISSUE TITLE
Endpoints with multiple parameters don't work.

### ISSUE THREAD

**Issue by rerb** [Hipo/Django-API-Playground#8]
E.g.:

   /credit/{credit-id}/category/{category-id}

'{credit-id}' gets replaced correctly when leaving that input box, but reverts back to '{credit-id}' when leaving the category-id input box.  Form action ends up being, e.g., /credit/{credit-id}/category/5

**Comment by pjambet** [comment]
So should we close this issue ? It seems it's been fixed
